import React from 'react'

export default function Methodology() {
  return (
    <div className="card">
      <h2>Methodology</h2>

      <h3>1. K-Means Clustering</h3>
      <p>
        We cluster villages using 12 village-amenity features (schools, ITIs, CHC, PHC,
        veterinary, bus, banks, mandi). Missing values are imputed with the median of
        the feature (never fabricated with district values). Features are standardized.
        K is chosen between 2 and 6 by silhouette score with random_state=42.
      </p>

      <h3>2. Opportunity Signal Engine</h3>
      <p>
        Transparent rule-based signals are derived from village-level census + amenity
        indicators and district-level context. Signals indicate opportunity potential
        in the available data - they are NOT proof of market demand.
      </p>

      <h3>3. Business Recommendation</h3>
      <p>
        Each of the 5 business categories receives a weighted opportunity score
        computed from village features and district context. Evidence is attached
        to every recommendation.
      </p>

      <h3>4. Budget Filter</h3>
      <p>
        Startup cost estimates (prototype/domain, not official) are compared to the
        user budget. Funding gap = max(required - budget, 0).
      </p>

      <h3>5. Random Forest - Proxy Supervised Model</h3>
      <p>
        There is no genuine village-level historical dataset of
        business-started to success/failure. We therefore train
        RandomForestClassifier on proxy labels generated by the
        argmax of the opportunity scoring engine. This is a prototype supervised
        layer, NOT a predictor of real-world business success.
      </p>

      <h3>6. Financial Simulator</h3>
      <p>
        Computes revenue, cost, profit, ROI, break-even and payback from user-provided
        assumptions. Payback requires positive monthly profit; break-even requires a
        positive contribution margin.
      </p>

      <h3>7. PMEGP</h3>
      <p>
        Government-scheme relevance shown for information. Current eligibility,
        subsidy and financing conditions must be verified with official PMEGP/KVIC
        sources before making decisions.
      </p>

      <h3>Data granularity</h3>
      <ul>
        <li><strong>Village-level:</strong> pca_villages.csv, village_clustering_dataset (1).csv</li>
        <li><strong>District-level context:</strong> b04, b24, crop_area, crop_production, dairy, aggregated amenities</li>
      </ul>

      <h3>Limitations</h3>
      <ul>
        <li>K-Means identifies similar village profiles - not demand.</li>
        <li>Opportunity signals are derived from available data.</li>
        <li>No genuine village-level business success labels exist; RF uses proxy labels.</li>
        <li>Financial results depend entirely on user assumptions.</li>
        <li>Startup cost estimates are prototype/domain figures, not official costs.</li>
        <li>Government scheme details must be verified officially.</li>
        <li>Some datasets are district-level context, never copied as village values.</li>
        <li>Missing data is never fabricated.</li>
      </ul>
    </div>
  )
}
